/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IdeRouteImport } from './routes/ide'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as ComponentRegistryRouteImport } from './routes/component-registry'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as ApiRuntimeHealthRouteImport } from './routes/api/runtime/health'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeRoute = IdeRouteImport.update({
  id: '/ide',
  path: '/ide',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentRegistryRoute = ComponentRegistryRouteImport.update({
  id: '/component-registry',
  path: '/component-registry',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRuntimeHealthRoute = ApiRuntimeHealthRouteImport.update({
  id: '/api/runtime/health',
  path: '/api/runtime/health',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/component-registry': typeof ComponentRegistryRoute
  '/design-system': typeof DesignSystemRoute
  '/ide': typeof IdeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/api/runtime/health': typeof ApiRuntimeHealthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/component-registry': typeof ComponentRegistryRoute
  '/design-system': typeof DesignSystemRoute
  '/ide': typeof IdeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/api/runtime/health': typeof ApiRuntimeHealthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/component-registry': typeof ComponentRegistryRoute
  '/design-system': typeof DesignSystemRoute
  '/ide': typeof IdeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/api/runtime/health': typeof ApiRuntimeHealthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/component-registry'
    | '/design-system'
    | '/ide'
    | '/sitemap.xml'
    | '/sign-in/$'
    | '/api/runtime/health'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/component-registry'
    | '/design-system'
    | '/ide'
    | '/sitemap.xml'
    | '/sign-in/$'
    | '/api/runtime/health'
  id:
    | '__root__'
    | '/'
    | '/component-registry'
    | '/design-system'
    | '/ide'
    | '/sitemap.xml'
    | '/sign-in/$'
    | '/api/runtime/health'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComponentRegistryRoute: typeof ComponentRegistryRoute
  DesignSystemRoute: typeof DesignSystemRoute
  IdeRoute: typeof IdeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SignInSplatRoute: typeof SignInSplatRoute
  ApiRuntimeHealthRoute: typeof ApiRuntimeHealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ide': {
      id: '/ide'
      path: '/ide'
      fullPath: '/ide'
      preLoaderRoute: typeof IdeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/component-registry': {
      id: '/component-registry'
      path: '/component-registry'
      fullPath: '/component-registry'
      preLoaderRoute: typeof ComponentRegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runtime/health': {
      id: '/api/runtime/health'
      path: '/api/runtime/health'
      fullPath: '/api/runtime/health'
      preLoaderRoute: typeof ApiRuntimeHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComponentRegistryRoute: ComponentRegistryRoute,
  DesignSystemRoute: DesignSystemRoute,
  IdeRoute: IdeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SignInSplatRoute: SignInSplatRoute,
  ApiRuntimeHealthRoute: ApiRuntimeHealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
